# ZMK Dongle configuration
CONFIG_ZMK_KEYBOARD_NAME="ErgoDox"

# Enable split & BLE split central role with 2 split peripherals (Left & Right halves)
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_BLE=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2
CONFIG_BT_MAX_CONN=7
CONFIG_BT_MAX_PAIRED=7

# Wireless transmission power (+8 dBm for strong stable link)
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Experimental BLE connectivity improvements
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y

# Dongle plugged into USB host: never sleep
CONFIG_ZMK_SLEEP=n

# Pure headless dongle (no display)
CONFIG_ZMK_DISPLAY=n

# ZMK Studio Support (on-the-fly keymap configuration over USB)
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n
